### PR TITLE
enable `rustls-platform-verifier` for docs.rs

### PR DESCRIPTION
**Pull request by flisky**

### CODE REVIEW

**Review by cpu — APPROVED** [review]
Good idea, thank you!

**Review by djc — APPROVED** [review]

**Review by djc — COMMENTED** [review]
Thanks -- would you mind keeping them in alphabetic order?

In rustls we've made the jump to `#![cfg_attr(docsrs, feature(doc_cfg, doc_auto_cfg))]`, that would be even better to follow here, if you want to spend a little time on that.

**Comment by flisky** [comment]
It seems `doc_auto_cfg` is already there in f9775bcc1c30b9a0c620ea6c623bbd8025e8494b by yourself, @djc:)

**Comment by djc** [comment]
Okay, thanks for the sorting!

**Pull request merged**
