### PR TITLE
Refresh example certificates

### LINKED ISSUE #173: Out-of-date example certificate
It seems the certificate in `/examples` is out of date.
```
cat examples/sample.pem | openssl x509 -noout -enddate
notAfter=Feb  3 16:07:04 2022 GMT
```

### PR DESCRIPTION
**Pull request by djc**
Fixes #173. This is basically a simplified version of https://github.com/rustls/rustls/tree/main/test-ca.

### CODE REVIEW

**Review by cpu — APPROVED** [review]

**Comment by djc** [comment]
@cpu would you be able to dig into these macOS CI failures? FWIW the tests pass locally on my macOS machine (ran them like ~10 times).

**Comment by cpu** [comment]
>  I'll see what I can figure out.

The problem is not related to this PR (it reproduces on `main`). I was able to trace this down to a bugfix in curl v7.88.0+. Only the MacOS builder is using this curl version (the Linux instances are on 7.58.0). 

I think this is safe to merge whenever it gets a +1 from a maintainer. I'll open a separate PR in the next hour or two with more information on what's going on with curl 7.88 and a fix.

**Comment by cpu** [comment]
> I'll open a separate PR in the next hour or two with more information on what's going on with curl 7.88 and a fix.
https://github.com/rustls/hyper-rustls/pull/193

**Comment by cpu** [comment]
Merging with one review since this is just test data.

**Pull request merged**
