### PR TITLE
Adding steps to run the examples

### PR DESCRIPTION
**Pull request by RichardoC**
Figured it would be better explicitly saying how to run the examples for those less experienced with Rust

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
(CI failures should be covered by #190.)

**Comment by RichardoC** [comment]
I can't rerun the workflows to get a green build. Mind re-triggering?

**Comment by RichardoC** [comment]
Mind rerunning now main is green?

**Comment by djc** [comment]
I reran the failing CI workflows, still some failures here though.

**Comment by RichardoC** [comment]
Need anything else from me @djc ?

**Comment by djc** [comment]
Nope, thanks!

**Pull request merged**
